x <- rnorm(1000, mean = 10, sd = 4)
install.packages("Przewodnik")
install.packages("e1071")
library("Przewodnik")
library("e1071")
tab <- table( daneSoc$wyksztalcenie)
barplot(tab, horiz = TRUE, las=1)
tab2 <- table( daneSoc$plec, daneSoc$wyksztalcenie)
barplot(tab2, las=1, beside = TRUE)
legend("topright", c('kobieta','mezczyzna'),fill=c("grey",'black'))
table(daneSoc$plec)
barplot(tab2, las=1, beside = TRUE, col=c('green', 'yellow'))
legend("topright", c('mezczyzna','kobieta'),fill=c('yellow','green'))
hist(x)
IQR(x)
hist(daneSoc$wiek, breaks = 25, main='Histogram zm wiek', las=1, probability=TRUE, ylab='Czestosc', xlab="wiek", col="grey", border = "white" )
boxplot(x)
boxplot(daneSoc$cisnienie.rozk, daneSoc$cisnienie.skur, horizontal = TRUE, names = c('Skurczowe','Rozkurczowe'))
boxplot(wiek~wyksztalcenie, data=daneSoc, ylab='Wiek', las=1,col='lightgrey', varwidth=TRUE)
plot(density(daneSoc$wiek), main="Rozklad wieku")
plot(density(daneSoc$wiek ,bw=1.5), main="Rozklad wieku")
ggplot(daneSoc, aes(x = wiek)) + geom_density() + labs(x = "Wzrost", y = "gêstoœæ")
plot(ecdf(x))
plot(ecdf(daneSoc$wiek), main = "Dystrybuanta wieku")
y <- dcauchy(x, location = 0, scale = 1, log = FALSE)
plot(density(y), main="gestosc")
y <- rcauchy(1000, location = 1, scale = 10)
plot(density(y), main="gestosc")
